name: Deploy

on:
  push:
    branches:
      - main

jobs:
  echo_secrets_and_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets and environment variables
        run: |
          echo "${{ secrets.TOKEN_SECRET }}"
